/**
 * Created by Andrew on 10.01.2022.
 */
@IsTest
private class VisitTriggerTest {
    @IsTest
    static void testBehavior() {
//        List<Contact> kids = TestDataFactory.createKids(2);
//        insert kids;

//        List<Visit__c> visitsYesterday = TestDataFactory.createVisits(kids, Date.today()-1);
//
//        Visit__c visit = new Visit__c(CreatedDate=Date.today(), Kid__c = kids.get(0).Id);
//        Visit__c duplicateVisit = new Visit__c(CreatedDate=Date.today(), Kid__c = kids.get(0).Id);


//        Test.startTest();
//        Database.SaveResult result = Database.insert(visit);
//        Database.SaveResult duplicateResult = Database.insert(visit);
//        Test.stopTest();
//
//        System.assert(result.isSuccess());
//        System.assert(!duplicateResult.isSuccess());
//        System.assertEquals('Kid has already been marked as present today', duplicateResult.errors[0].getMessage());

    }
}